import Head from 'next/head'
import '../styles/globals.css'
import LayoutWrapper from '../components/LayoutWrapper'

function MyApp({ Component, pageProps }) {
  return (
  <>
    <Head>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <title>Viva La Zoom</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <LayoutWrapper>
      <Component {...pageProps} />
    </LayoutWrapper>
  </>
  )
}

export default MyApp
